compute_environment: LOCAL_MACHINE
debug: true
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 0,1,2,3,4,5
#machine_rank: 0 -- instead, we will need to pass in $RANK
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 6
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

#main_process_port: 63333  -- we use the $MASTER_PORT
#main_process_ip: NA -- we willa lso need to pass in $MASTER_ADDR for master_addr


# compute_environment: LOCAL_MACHINE
# debug: true
# distributed_type: MULTI_GPU
# downcast_bf16: 'no'
# enable_cpu_affinity: false
# gpu_ids: all
# machine_rank: 0
# main_process_ip: '10'
# main_process_port: 9
# main_training_function: main
# mixed_precision: fp16
# num_machines: 10
# num_processes: 60
# rdzv_backend: static
# same_network: true
# tpu_env: []
# tpu_use_cluster: false
# tpu_use_sudo: false
# use_cpu: false

